# Generated by Django 3.0 on 2020-03-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('phase', models.CharField(choices=[('B', 'Backlog'), ('IP', 'In progress'), ('RD', 'Ready to deploy'), ('L', 'Live'), ('R', 'Retired')], max_length=15)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
