# Generated by Django 3.0 on 2020-03-27 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0002_auto_20200326_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='theme',
            field=models.CharField(blank=True, choices=[('EC', 'Ext. collaboration'), ('IC', 'Int. collaboration'), ('UG', 'User guidance'), ('MPP', 'Performance'), ('ES', 'Enabling SECRET')], max_length=15),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
