# Generated by Django 3.0 on 2020-03-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20200328_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organisation',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
