# Generated by Django 3.0.3 on 2020-03-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20200328_2140'),
        ('upload', '0005_profile_organisation'),
    ]

    operations = [
    ]
